.PHONY: clear

table1: table.c
	cc -o table1 -D CASE=1 -Wall table.c

table2: table.c
	cc -o table2 -D CASE=2 -Wall table.c

table3: table.c
	cc -o table3 -D CASE=3 -Wall table.c

clear:
	rm -f table1 table2 table3
